In [41]:
import numpy as np
import pandas as pd

In [51]:
input_data=np.array([[0,0,0],
                    [0,0,1],
                    [0,1,0],
                     [0,1,1],
                    [1,1,0]])
output_labels= np.array([[0],
       [1],
       [1],
       [0],
       [0]])
print(input_data)
print(output_labels)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]]
[[0]
 [1]
 [1]
 [0]
 [0]]


In [52]:
def activate(x):
    return 1/(1+np.exp(-x))

In [53]:
def transfer_derivative(output):
    return output*(1-output)

In [54]:
np.random.seed(4)
w0=np.random.random((3,5))
w1=np.random.random((5,1))
print(w0)
print(w1)

[[0.96702984 0.54723225 0.97268436 0.71481599 0.69772882]
 [0.2160895  0.97627445 0.00623026 0.25298236 0.43479153]
 [0.77938292 0.19768507 0.86299324 0.98340068 0.16384224]]
[[0.59733394]
 [0.0089861 ]
 [0.38657128]
 [0.04416006]
 [0.95665297]]


In [55]:
def feed_forward(input_data):
    layer0=input_data
    layer1=activate(np.dot(layer0,w0))
    layer2=activate(np.dot(layer1,w1))
    
    return layer0,layer1,layer2


In [56]:
def backpropogate(j,layer0,layer1,layer2,w1,w0):
    l2_error=output_labels-layer2
    if(j%1000)==0:
        print("error:"+ str(np.mean(np.abs(l2_error))))
        
    l2_grad=l2_error*transfer_derivative(layer2)
    
    l1_error=l2_grad.dot(w1.T)
    l1_grad=l1_error*transfer_derivative(layer1)
    
    w1 += layer1.T.dot(l2_grad)
    w0 += layer0.T.dot(l1_grad)
    
    

In [60]:
for i in range(10000):
    layer0,layer1,layer2=feed_forward(input_data)
    backpropogate(i,layer0,layer1,layer2,w1,w0)

error:0.014998149482668935
error:0.014218154814036706
error:0.0135396629345646
error:0.012942029742134185
error:0.012410063244638546
error:0.01193230636128739
error:0.011499936536977947
error:0.011106036544164918
error:0.01074509715922144
error:0.010412669417610128


In [64]:
layer0,layer1,layer2=feed_forward([[1,1,1]])

In [65]:
print(layer2)

[[0.00072236]]
