In [1]:
import numpy as np
import pandas as pd

In [2]:
input_data=np.array([[0,0,0],
                    [0,0,1],
                    [0,1,0],
                     [0,1,1],
                     [1,1,0],
                    [1,0,0]])
output_labels= np.array([[0],
       [1],
       [1],
       [1],
        [1],
       [1]])
print(input_data)
print(output_labels)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 0 0]]
[[0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [3]:
def activate(x):
    return 1/(1+np.exp(-x))

In [4]:
def transfer_derivative(output):
    return output*(1-output)

In [5]:
np.random.seed(4)
w0=np.random.random((3,4))-1
w1=np.random.random((4,1))-1


In [6]:
def feed_forward(input_data):
    layer0=input_data
    layer1=activate(np.dot(layer0,w0))
    layer2=activate(np.dot(layer1,w1))
    
    return layer0,layer1,layer2

In [7]:
def backpropogate(j,layer0,layer1,layer2,w1,w0):
    l2_error=output_labels-layer2
    if(j%1000)==0:
        print("error:"+ str(np.mean(np.abs(l2_error))))
        
    l2_grad=l2_error*transfer_derivative(layer2)
    
    l1_error=l2_grad.dot(w1.T)
    l1_grad=l1_error*transfer_derivative(layer1)
    
    w1 += layer1.T.dot(l2_grad)
    w0 += layer0.T.dot(l1_grad)

In [8]:
for i in range(10000):
    layer0,layer1,layer2=feed_forward(input_data)
    backpropogate(i,layer0,layer1,layer2,w1,w0)

error:0.5861251707975204
error:0.025303446800603136
error:0.016099174952408146
error:0.012540929538995715
error:0.010557510880838792
error:0.00926058124567451
error:0.008331991019767249
error:0.007626898552563176
error:0.0070689958360640555
error:0.0066138857438192205


In [9]:
layer0,layer1,layer2=feed_forward([[0,0,0]])

In [10]:
print(layer2)

[[0.01407826]]
